<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <Authors>Ilia Tikhonov</Authors>
        <PackageProjectUrl>https://github.com/tihilv/Omtt</PackageProjectUrl>
        <RepositoryUrl>https://github.com/tihilv/Omtt</RepositoryUrl>
        <Version>1.2.6</Version>
        <NoWarn>$(NoWarn);NU1901;NU1902;NU1903;NU1904;NETSDK1138</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
</Project>
