<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Omtt</Title>
        <Description>One More Template Transformer - powerful and flexible template engine for .NET</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Omtt.Api\Omtt.Api.csproj" />
      <ProjectReference Include="..\Omtt.Parser\Omtt.Parser.csproj" />
    </ItemGroup>

</Project>
