<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Omtt Statements</Title>
        <Description>Statement processor library for Omtt (One More Template Transformer)</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Omtt.Api\Omtt.Api.csproj" />
    </ItemGroup>

</Project>
