<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Omtt Parser</Title>
        <Description>Text parser library for Omtt (One More Template Transformer)</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Omtt.Api\Omtt.Api.csproj" />
      <ProjectReference Include="..\Omtt.Statements\Omtt.Statements.csproj" />
    </ItemGroup>

</Project>
