<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Omtt.Generator</RootNamespace>
        <Title>Omtt QR Addon</Title>
        <Description>QR addon for Omtt (One More Template Transformer)</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="QRCoder" Version="1.4.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Omtt.Api\Omtt.Api.csproj" />
      <ProjectReference Include="..\Omtt.Generator\Omtt.Generator.csproj" />
    </ItemGroup>

</Project>
